name: Test

on:
  pull_request:
    types: [opened]

jobs:
  thank-you:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}